
name: Email Workflow
on:
  push: 
    branches: [ main ]

jobs:
  send-mail:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  #
          
      - name: Get commit details
        id: commit-details
        run: |
            echo "diff<<EOF" >> $GITHUB_OUTPUT
            git diff --unified=3 ${{ github.sha }}~1..${{ github.sha }}
            echo "EOF" >> $GITHUB_OUTPUT
            echo "message<<EOF" >> $GITHUB_OUTPUT
            echo "${{ github.event.head_commit.message }}" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT

          
      - name: Extract File Changes
        id: file-changes
        run: |
          echo "modified_files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} --diff-filter=M | tr '\n' ',')" >> $GITHUB_OUTPUT
          echo "added_files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} --diff-filter=A | tr '\n' ',')" >> $GITHUB_OUTPUT
          echo "removed_files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} --diff-filter=D | tr '\n' ',')" >> $GITHUB_OUTPUT
          
      - name: Send Mail
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
        # Server port, default 25:
          server_port: 465
        # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
        # Optional (recommended) mail server username:
          username: ${{secrets.MAIL_USERNAME}}
        # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
        # Required mail subject:
          subject: Github Actions job result
        # Required recipients' addresses:
          to: robertgriffintm@gmail.com
        # Required sender full name (address can be skipped):
          from: Bobby Griffin <bob.griff.29@gmail.com> # <user@example.com>
        # Optional plain body:
          body: |
            Repository: ${{ github.repository }}
            
            Commit Message:
            ${{ github.event.head_commit.message }}
                     
            Modified Files:
            ${{ steps.file-changes.outputs.modified_files }}
            
            Added Files:
            ${{ steps.file-changes.outputs.added_files }}
            
            Removed Files:
            ${{ steps.file-changes.outputs.removed_files }}
            
            Full Diff:
            ```
            ${{ steps.commit-details.outputs.message }}
            ```
            Committed by: ${{ github.event.pusher.name }}
            
        # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
        # Optional converting Markdown to HTML (set content_type to text/html too):
        #  convert_markdown: true
        # Optional attachments:
         # attachments: attachments.zip,git.diff,./dist/static/*.js
        # Optional priority: 'high', 'normal' (default) or 'low'
          priority: low
      
